project:
  type: website
  output-dir: docs

website:
  title: "SRDP Team Website"
  navbar:
    pinned: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Datasets"
        file: datasets/index.qmd

    sidebar:
      - id: datasets
        title: "Datasets"
        style: "docked"
        background: light
        collapse-level: 2
        contents:
            - datasets/index.qmd
            - datasets/demands.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

