project:
  type: website

website:
  title: "SRDP Team Website"
  navbar:
    pinned: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Dataset"
        file: datasets/index.qmd

    sidebar:
      - title: "Datasets"
        background: light
        contents:
            - text: "Demands"
              file: datasets/demands.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

