project:
  type: website
  output-dir: docs

website:
  title: "SRDP Team Website"
  navbar:
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Datasets"
        href: datasets/index.qmd
      - icon: github
        href: https://github.com/Fragmentation-Project
        aria-label: GitHub
      - icon: slack
        href: https://join.slack.com/t/fragprojectco-xiy4179/shared_invite/zt-1t2pqnzgw-GFNHWim1Wa0U2GcJZwXTFA
        aria-label: Slack

  sidebar:
    - title: "Datasets"
      style: "docked"
      contents:
        - datasets/index.qmd
        - datasets/groups.qmd
        - datasets/orgs.qmd
        - datasets/demands.qmd
        - datasets/concessions.qmd
        - datasets/tactics_nv.qmd
        - datasets/tactics_v.qmd
        - datasets/alias.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

